### PR TITLE
port some example agents, fix bug in core

### PR DESCRIPTION
**Pull request by andyk**
Ported 2 of the example agents to the new changes in core. DQN agent isn't solving cartpole or mountaincar right now when run with the default settings, thought it appears to be running and updating the policy as it runs.

### CODE REVIEW

**Review by nickjalbert — APPROVED** [review]
LGTM!

**Comment by nickjalbert** [comment]
One q: can we reinstate any tests with these changes?

**Comment by andyk** [comment]
> One q: can we reinstate any tests with these changes?

Good question. Probably!

**Comment by andyk** [comment]
> 
> 
> > One q: can we reinstate any tests with these changes?
> 
> Good question. Probably!

But we *might* need to tweak the tests given the new structure agentos.run_agent()

**Pull request merged**
